### ISSUE TITLE
280v.xml intermarginal scholion

### ISSUE THREAD

**Issue by DocTaz** [hmteditors/leiden2017#2]
In the intermarginal scholion on 21.542 there are 2 supralinear glyphs that do not seem to make sense. We read θι (theta-iota), but cannot make any sense out of it. We suspect that there has been some rasura under οὕτω σφεδανόν and that θι is somehow a remnant of this rasura. We are not sure how to mark up this hypothetical rasura. 
urn:cite:hmt:vaimg.VA280VN-0782@0.428,0.4565,0.076,0.0315

**Comment by MGelein** [comment]
Closed as >1 year old
