### ISSUE TITLE
Interlinear #7 on 277r

### ISSUE THREAD

**Issue by Bijvoets** [hmteditors/leiden2017#3]
The seventh interlinear on folio 277r, commenting on Iliad book 21, verse 366, is challenging to decipher:

urn:cite:hmt:vaimg.VA277RN-0447@0.506,0.4542,0.143,0.048

It seems to start with: πνοη δ' ανα
and end with: κ του πυρος

What to make out of the central (three?) characters?

**Comment by MGelein** [comment]
Closed. > 1 year old
