### ISSUE TITLE
Citation range in scholia?

### ISSUE THREAD

**Issue by SEBoreel** [hmteditors/leiden2017#4]
We encountered a citation in a scholion in 281v that covers two lines (<cit><ref type=”urn”>urn:cts:greekLit:tlg0012.tlg001:21.605_606</ref><q> citation </q></cit>). How do we annotate this in GitHub? Should we use a dash (ie 605_606)?

**Comment by StephanieML** [comment]
urn:cts:greekLit:tlg0012.tlg001:21.605-21.606
