### ISSUE TITLE
Add new name: Erymas

### ISSUE THREAD

**Issue by PhilipMuijtjens** [hmteditors/leiden2017#5]
This name turns up twice: in 16.345 (f. 212v) and 16.415 (f. 214r). Two Trojans were called Erymas. The first one was speared through the mouth and subsequently killed by Idomeneus (16.345). The second Erymas was killed by Patroclus (16.415). 

For 16.415: urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.2931,0.4456,0.09175,0.01881

**Comment by MGelein** [comment]
Niet de juiste locatie. Verplaats naar https://github.com/homermultitext/hmt-authlists/issues.
