### ISSUE TITLE
Add new name: Amphoteros

### ISSUE THREAD

**Issue by PhilipMuijtjens** [hmteditors/leiden2017#6]
This person appears only in 16.415 (f. 214r). He was killed by Patroclus. 

See:  urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.4189,0.4462,0.09285,0.02254

**Comment by MGelein** [comment]
Niet de juiste locatie. Verplaats naar https://github.com/homermultitext/hmt-authlists/issues.
