### ISSUE TITLE
Add new name: Pronoös

### ISSUE THREAD

**Issue by ManonJunggeburt** [hmteditors/leiden2017#7]
Pronoös appears in 16.399 (f. 213v.) Pronoös was killed by Patroclus.

See: urn:cite2:hmt:vaimg.2017a:VA213VN_0715@0.5709,0.6422,0.08014,0.01757

**Comment by MGelein** [comment]
Niet de juiste locatie. Verplaats naar https://github.com/homermultitext/hmt-authlists/issues.
