### ISSUE TITLE
Add new name: Erylaos

### ISSUE THREAD

**Issue by PhilipMuijtjens** [hmteditors/leiden2017#8]
Erylaos is mentioned in 16.411 (f. 214r). He was a Trojan who was killed by stone thrown by Patroclus.

See: urn:cite2:hmt:vaimg.2017a:VA214RN_0385@0.3043,0.3698,0.08419,0.02158

**Comment by MGelein** [comment]
Niet de juiste locatie. Verplaats naar https://github.com/homermultitext/hmt-authlists/issues.
